export enum sagaTypes {
  STREAM_AUTH_STATECHANGE = 'STREAM_AUTH_STATECHANGE',
  STREAM_AUTH_STATECHANGE_CANCEL = 'STREAM_AUTH_STATECHANGE_CANCEL',

  STREAM_EVENTS = 'STREAM_EVENTS',
  STREAM_EVENTS_CANCEL = 'STREAM_EVENTS_CANCEL',

  STREAM_NOTIFICATIONS = 'STREAM_NOTIFICATIONS',
  STREAM_NOTIFICATIONS_CANCEL = 'STREAM_NOTIFICATIONS_CANCEL',

  STREAM_FEEDBACKS = 'STREAM_FEEDBACKS',
  STREAM_FEEDBACKS_CANCEL = 'STREAM_FEEDBACKS_CANCEL',

  STREAM_PRAYERS = 'STREAM_PRAYERS',
  STREAM_PRAYERS_CANCEL = 'STREAM_PRAYERS_CANCEL',

  STREAM_LOCATIONS = 'STREAM_LOCATIONS',
  STREAM_LOCATIONS_CANCEL = 'STREAM_LOCATIONS_CANCEL'
}
